package tc_tests;
unit LocationUnit;

import tc_tests.facts.Location;

query getLocations(String x)
    $x: /locations[thing==x]
end

query isContainedIn( String x, String y )
    /locations[thing := x, location := y]
    or
    (/locations[z := thing, location := y] and isContainedIn(x, z;))
end


// NOT WORKING unbound query, accessing singletonstore BEFORE query
rule "Location Inference"
no-loop
when
    $go: /go[this=="go1"]
    isContainedIn($x, $y;)
    (not /locations[thing== $x, location== $y, inferred==false])
then
    System.out.println($go);
    System.out.println("Inferred: " + $x + " IN " + $y);
    Location loc = new Location($x, $y, true);
    locations.addLogical(loc);
end

//// WORKING completely unbound query
// rule "Location Inference"
// no-loop
// when
//     isContainedIn($x, $y;)
//     (not /locations[thing== $x, location== $y, inferred==false])
// then
//     System.out.println("Inferred: " + $x + " IN " + $y);
//     Location loc = new Location($x, $y, true);
//     locations.addLogical(loc);
// end

//// WORKING accessing global and bind it to first query arg
// rule "Location Inference"
// no-loop
// when
//     $x: /testGlobal
//     isContainedIn($x, $y;)
//     (not /locations[thing== $x, location== $y, inferred==false])
// then
//     System.out.println("Inferred: " + $x + " IN " + $y);
//     Location loc = new Location($x, $y, true);
//     locations.addLogical(loc);
// end

//// WORKING unbound query, accessing singletonstore AFTER query
// rule "Location Inference"
// no-loop
// when
//     isContainedIn($x, $y;)
//     $go: /go[this=="go1"]
//     (not /locations[thing== $x, location== $y, inferred==false])
// then
//     System.out.println($go);
//     System.out.println("Inferred: " + $x + " IN " + $y);
//     Location loc = new Location($x, $y, true);
//     locations.addLogical(loc);
// end